name: "jamo2b"
platform: "pytorch_libtorch"
max_batch_size: 10
dynamic_batching { preferred_batch_size: [ 5 ]}
instance_group [
    {
      count: 2
      kind: KIND_CPU
    }
]
input [
  {
    name: "input0"
    data_type: TYPE_INT16
    dims: [ -1 ]
  }
]
output [
  {
    name: "output0"
    data_type: TYPE_INT16
    dims: [ -1 ]
  }
]